--Exploratory Data Analysis

--DataBase Exploration
SELECT * FROM INFORMATION_SCHEMA.TABLES 
SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Sales.orders_combined'

--Dimensions Exploration
--Explore All countries our customers come from.
SELECT distinct(country) FROM sales.Customers
--Explore All Categories and Products
SELECT product,Category FROM sales.Products

--Date Exploration
--Find the Date of First and Last order and How many years of sales are available
SELECT min( OrderDate) as first_order	,
max(OrderDate) as last_order,
DATEDIFF(year,min( OrderDate),max(OrderDate)) order_range_years
FROM Sales.orders_combined
--Find the youngest and oldest Employees and Ages
SELECT MIN(birthdate)as oldest,
MAX(birthdate) as youngest ,
DATEDIFF(year,MIN(birthdate),GETDATE()) OLDEST_AGE,
DATEDIFF(year,MAX(birthdate),GETDATE()) YOUNGEST_AGE
from sales.Employees

--Measures Exploration
-- Find the Total Sales
SELECT SUM(sales) AS total_sales FROM sales.orders_combined
--Find How many items are sold
SELECT SUM(quantity) AS no_of_items FROM sales.orders_combined
--Find the average selling price
SELECT AVG(price) AS total_sales FROM sales.Products
--Find the total number of Orders
SELECT COUNT(OrderID) AS total_orders FROM sales.orders_combined
SELECT COUNT(DISTINCT(OrderID)) AS total_orders FROM sales.orders_combined
--Find the total number of Products
SELECT COUNT(ProductID) AS total_orders FROM sales.Products
--Find the total number of customers
SELECT COUNT(customerID) AS total_orders FROM sales.Customers
--Find the total number of customers that has placed an order
SELECT COUNT(distinct(customerID)) AS total_orders FROM sales.orders_combined
--Generate a report that shows all key metrics of the business
SELECT 'Total sales' AS measure_name,SUM(sales) AS measure_value FROM sales.orders_combined
UNION ALL
SELECT 'Total Quantity',SUM(quantity)FROM sales.orders_combined
UNION ALL
SELECT 'Average price',AVG(price) FROM sales.Products
UNION ALL
SELECT 'Total no. of orders' ,COUNT(*)  FROM sales.orders_combined
UNION ALL
SELECT 'Total no. of products', COUNT(productID)  FROM sales.Products
UNION ALL
SELECT 'Total no. of customers' ,COUNT(customerID)  FROM sales.Customers
UNION ALL
SELECT 'Total no. of customers with orders',COUNT(distinct(customerID))  FROM sales.orders_combined

--Magnitude Analysis
-----Find total customers by countries
select country,
count(customerID) as total_customers 
from sales.Customers 
group by country
order by total_customers desc
---Find total Employees by gender
select gender,
count(EmployeeID) as total_employees
from sales.Employees
group by gender
order by total_employees desc

---Find total products by category
select category,
count(productID) as total_products 
from sales.Products
group by category
order by total_products desc

---what is the average cost in each category?
select category,
avg(price) as avg_cost
from sales.Products
group by category
order by avg_cost desc

--total revenue generated by each customer
select c.customerID,firstname+' '+coalesce(lastname,'') as Name,sum(sales) as total
from sales.Customers c 
left join sales.orders_combined f 
on c.customerID=f.customerID
group by c.customerID,firstname,lastname
order by total desc
--The distribution of sold items across countries
select c.country,sum(quantity) as total
from sales.Customers c 
left join sales.orders_combined o 
on c.customerID=o.customerID
group by country
order by total desc

--Ranking Analysis
--Which 3 products generate the highest revenue?
select top 3 
p.product,
sum(o.sales) as total_revenue
from sales.orders_combined  o
left join sales.Products p
on o.productID=p.productID
group by p.product
order by total_revenue desc
--3 worst performing products in terms of sales
select top 3 
p.product,
sum(o.sales) as total_revenue
from sales.orders_combined  o
left join sales.Products p
on o.productID=p.productID
group by p.product
order by total_revenue 

--Which sales person generates highest revenue
select TOP 1
e.FirstName+''+coalesce(e.LastName,'') as EmployeeName,
sum(o.sales) as total_revenue
from sales.orders_combined  o
left join sales.Employees e
on o.SalesPersonID=e.EmployeeID
group by e.FirstName+''+coalesce(e.LastName,'')
order by total_revenue desc

